### ISSUE TITLE
enviroment requirement

### ISSUE THREAD

**Issue by 98wh** [zzaebok/KGCN-pytorch#3]
Can you give some enviroment requirements about this repository? Thanks~

**Comment by zzaebok** [comment]
Hi,

python 3.7.7
CUDA 10.0

pytorch==1.4.0
pandas==1.0.5
scikit-learn==0.23.1
numpy==1.18.5
matplotlib==3.2.2

Thank you :)

**Comment by 98wh** [comment]
Thanks for sharing the requirements :)
