### ISSUE TITLE
Request to use your code

### ISSUE THREAD

**Issue by Ki-Seki** [zzaebok/KGCN-pytorch#8]
Hi, zzaebok.

I'm Shichao Song, from Henan University of Economics and Law, China. Your PyTorch implementation of KGCN is brilliant. I am wondering if you could please allow me to modify and cite your code for my thesis. If yes, that will be a great honor to me. Thank you for your patience to read this.

Best regards
Shichao Song

**Comment by zzaebok** [comment]
Hi Shichao,

You are free to fork my code and modify it.
However, as you know, this is just a Pytorch version implementation for this work (https://arxiv.org/abs/1904.12575).

Therefore, if it is about modifying the architecture and writing papers and so on, please check with the author of the paper.

Thanks!

**Comment by Ki-Seki** [comment]
Thank you for your support!
